### ISSUE TITLE
Need to do this on UI Thread. Crashed when I ran it

### ISSUE THREAD

**Issue by ranjjose-chaz** [yasin-ashraf/hubblerAssign#1]
https://github.com/yasin-ashraf/hubblerAssign/blob/baf36311e627cd4427bd24a877d2f3fb8502a9eb/app/src/main/java/com/yasin/hubbler/ReportsActivity.java#L53

**Comment by yasin-ashraf** [comment]
Fixed. Could have done this better with LiveData. But thought it is a little too heavy for a simple app like this. 
And, We could do all the database fetching in the main thread itself. But did it in a different thread in case there is a LONG set of fields to fetch from DB.
