### ISSUE TITLE
Support for field type "composite" 

### ISSUE THREAD

**Issue by ranjjose-chaz** [yasin-ashraf/hubblerAssign#2]
The composite field should be **displayed fullscreen** (like how the add report page is shown). A composite field can have **any other field including another composite field**. Ideally, the implementation should be such that it works to **nth level**
 
Sample input JSON:
```

[{
		"field-name": "name",
		"type": "text",
		"required": true
	},
	{
		"field-name": "Zone",
		"type": "dropdown",
		"options": ["A", "B", "C", "D"]
	},
	{
		"field-name": "age",
		"type": "number"
	},
	{
		"field-name": "address",
		"type": "composite",
		"fields": [{
				"field-name": "Address line1",
				"type": "text",
				"required": true
			},
			{
				"field-name": "Address line2",
				"type": "text"
			},
			{
				"field-name": "City",
				"type": "text",
				"required": true
			},
			{
				"field-name": "State",
				"type": "text",
				"required": true
			}

		],
		"required": false
	}
]
```

**Comment by yasin-ashraf** [comment]
This one took a lot of time. 'AddReportFragment' is being reused to the nth level. Due to difficulties in passing data to a fragment in back-stack, fragment back-stack is completely avoided.
The code has become less readable after adding this feature. :dagger:
