### ISSUE TITLE
General cleanliness 

### ISSUE THREAD

**Issue by ranjjose-chaz** [yasin-ashraf/hubblerAssign#4]
Try to minimise the following:
- [x] Hardcoded strings
       - Move all hardcoded strings to constants file or strings.xml
- [x] Code duplication
- [x] Large methods
       - Ideally, no method should be larger than 20-25 lines and one method should do only one thing (primarily) - Single responsibility principle (SRP)

**Comment by yasin-ashraf** [comment]
I have refactored the code as much as I can. There are a few methods where there are a high number of parameters. I hope other issues are fixed.
