### ISSUE TITLE
Issue with composite field  

### ISSUE THREAD

**Issue by ranjjose-chaz** [yasin-ashraf/hubblerAssign#6]
In the current `file.json`, if you go inside the `address` composite field and fill some data and click done and come back, the data filled in the outer form (that is `name`, `email` and `age`) is getting cleared. This is happening only for the `address` field and not with other composite fields.

**Comment by yasin-ashraf** [comment]
The problem was with 'compositefieldName' being null while setting the tag for edittext. Fixed now by passing a string 'a report' to the first instance of 'AddReportFragment'.
